import 'dotenv/config'
import { IGeneratedPost } from './IGeneratedPost'
import { GoogleGenAI } from '@google/genai'

export class GeminiService {
  private genAI: GoogleGenAI

  constructor() {
    const apiKey = process.env.GOOGLE_API_KEY
    if (!apiKey) {
      throw new Error('GOOGLE_API_KEY is not defined in .env file')
    }
    this.genAI = new GoogleGenAI({
      apiKey: apiKey,
    })
  }

  public async generatePostContent(topic: string): Promise<IGeneratedPost> {
    const prompt = `
      Generate a blog article on the topic "${topic}".
      The article should be SEO-optimized and follow an informative tone.
      Your response MUST be a valid JSON object, with no additional text or formatting before or after it.
      Use the following JSON structure:
      {
        "title": "An engaging and SEO-optimized title",
        "body": "The full article content in Markdown format. Include headings (##), lists, and bold text for structure.",
        "slug": "a short and descriptive slug for the URL",
        "meta_title": "A meta title for Google with a maximum of 60 characters"
      }
    `

    const modelContent = this.genAI.models.generateContent({
      model: 'gemini-1.5-flash',
      contents: prompt,
    })

    try {
      const result = await modelContent
      const text = result.text

      if (!text) throw new Error('No content generated by Gemini.')

      const jsonString = text
        .replace(/```json/g, '')
        .replace(/```/g, '')
        .trim()

      const parsedContent: IGeneratedPost = JSON.parse(jsonString)
      return parsedContent
    } catch (error) {
      console.error('Error generating content with Gemini:', error)
      throw new Error('Failed to generate post content.')
    }
  }
}
